### ISSUE TITLE
SQLite Version

### ISSUE THREAD

**Issue by MinIsMin** [doctorluk/ulx-karma-betting#1]
Karma verwetten ist eine gute Idee.

Aber was ist der Sinn von _KARMABET_USE_MYSQL_? Nichts funktioniert, wenn es auf false gesetzt ist.

Es wäre gut, wenn du eine SQLite version hinzufügen könntest; SQLite funktioniert ohne Konfiguration.

Es funktioniert so:

```
sql.Query( "SET NAMES 'utf8';" )
sql.Query( "CREATE TABLE IF NOT EXISTS karmabet (id int(32) unsigned NOT NULL AUTO_INCREMENT, bet_id int(32) unsigned NOT NULL, name text COLLATE utf8_unicode_ci NOT NULL, steamid text COLLATE utf8_unicode_ci NOT NULL, amount int(11) NOT NULL, date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;" )
```

Ich habe derzeit keine Zeit, deinen Code umzuschreiben, deshalb bitte ich dich wenn du Zeit findest, es zu tun.

**Comment by doctorluk** [comment]
Werde ich mir eventuell mal anschauen, ob ich noch SQLite mit einbaue. Kann es allerdings nicht wirklich ausführlich testen. Aber es sollte nicht so viel Testaufwand benötigen.
Danke für das Funktionsbeispiel!

**Comment by MinIsMin** [comment]
Ich kann es auf meinem Backup Server testen.
Speichere deinen Arbeitsfortschritt in einem neuem Branch (nicht "master" sondern zB. "beta").

**Comment by doctorluk** [comment]
Muss ich mich nur mal einlesen, wie man mehrere Branches macht. Sobald ich Zeit/Lust habe, schaue ich mir das mal an.

**Comment by doctorluk** [comment]
Erster Draft ist fertig. Weiß nur noch nicht, wie ich die Datumsvergleiche einbaue. Tabellenerstellung, Insertion und !mybets funktionieren bereits.
Siehe 5665c6e520a2348ce9020ac9f6f328c3b256ea0c

**Comment by doctorluk** [comment]
Gehe mal davon aus, das alles funktioniert. Kannst gerne mal den sqlite Branch ausprobieren.

**Comment by doctorluk** [comment]
Wieso close ich das eigentlich, wenn noch gar nicht feststeht, ob es funktioniert? Sag bitte Bescheid, ob SQLite auch ohne Probleme funktioniert.

**Comment by MinIsMin** [comment]
Wenn die ULX Befehle benutzt werden:

```
[Karmabet] showBestBetters table results:

[ULib] lua/includes/extensions/table.lua:711: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. GetKeys - lua/includes/extensions/table.lua:711
    3. PrintTable - lua/includes/util.lua:42
     4. karmabet_showBestBetters - addons/betting/lua/autorun/server/sv_karma_betting_sqlite.lua:61
      5. call - addons/betting/lua/ulx/modules/sh/betting.lua:47
       6. __fn - lua/ulib/shared/commands.lua:943
        7. unknown - lua/ulib/shared/commands.lua:1296
         8. Run - lua/includes/modules/concommand.lua:54
          9. unknown - lua/ulib/shared/commands.lua:1311
           10. unknown - lua/includes/modules/concommand.lua:54


[Karmabet] showWorstBetters table results:

[ULib] lua/includes/extensions/table.lua:711: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. GetKeys - lua/includes/extensions/table.lua:711
    3. PrintTable - lua/includes/util.lua:42
     4. karmabet_showWorstBetters - addons/betting/lua/autorun/server/sv_karma_betting_sqlite.lua:98
      5. call - addons/betting/lua/ulx/modules/sh/betting.lua:61
       6. __fn - lua/ulib/shared/commands.lua:943
        7. unknown - lua/ulib/shared/commands.lua:1296
         8. Run - lua/includes/modules/concommand.lua:54
          9. unknown - lua/ulib/shared/commands.lua:1311
           10. unknown - lua/includes/modules/concommand.lua:54
```

**Comment by doctorluk** [comment]
Hast du schon Einträge in deiner SQLite Datenbank vom karmabet, oder existiert noch kein Eintrag?

**Comment by MinIsMin** [comment]
Es sollten welche existieren, ich habe mehrere Wetten durchgeführt

**Comment by doctorluk** [comment]
Das klingt nicht gut... Wenn durch das Query nil zurück kommt, dann lief was falsch. false wäre eine leere Tabelle.
Was ist, wenn du die Zeilen 61 und 98 in der sv_karma_betting_sqlite.lua auskommentierst?

**Comment by doctorluk** [comment]
Kannst du mir deine sv.db zukommen lassen (sofern diese keine empfindlichen Daten enthält)? Findest sie in `/garrysmod/sv.db`

**Comment by MinIsMin** [comment]
Nil bleibt Nil:

```
[ULib] addons/betting/lua/autorun/server/sv_karma_betting_sqlite.lua:63: attempt to get length of local 'list' (a nil value)
  1. karmabet_showBestBetters - addons/betting/lua/autorun/server/sv_karma_betting_sqlite.lua:63
   2. call - addons/betting/lua/ulx/modules/sh/betting.lua:47
    3. __fn - lua/ulib/shared/commands.lua:943
     4. unknown - lua/ulib/shared/commands.lua:1296
      5. Run - lua/includes/modules/concommand.lua:54
       6. unknown - lua/ulib/shared/commands.lua:1311
        7. unknown - lua/includes/modules/concommand.lua:54
```

Worst Bet funktioniert jedoch.

**Comment by doctorluk** [comment]
Wenn !worstbets geht, ist die Summe deiner gesetzten Wetten also negativ? Dann würde es Sinn ergeben, wenn er nil liefert, weil keine Tabelle zurückgegeben wird, in der Spieler >0 Karma gewonnen haben.

Hab mal eine neue Version gepusht. Versuch es damit mal.

**Comment by MinIsMin** [comment]
Funktioniert alles, keine Lua Fehler.
Wäre es nicht gut, wenn die Spectator/Toten (Wettberechtigte Spieler) rechts die Wettliste sehen?
Das gibt eine bessere Übersicht, wenn mehrere wetten.

**Comment by doctorluk** [comment]
Habe das hier dann mal geschlossen. Für weitere Features bitte ein neues Issue öffnen. :)
