### ISSUE TITLE
Derma GUI

### ISSUE THREAD

**Issue by MinIsMin** [doctorluk/ulx-karma-betting#4]
Wäre es für dich möglich, ein Derma GUI für Befehle hinzuzufügen?
Manche Personen finden ein GUI schöner als reinen Text.
Ich selbst kann keine Derma GUI's programmieren, sonst würde ich einen Pull einreichen.
Am sinnvollsten wäre es für !bet. Es sollte wie folgt aufgebaut sein:

Überschrift (Karma Verwetten)
Beschreibung (Anzahl des Karmas) - DNumSlider
Beschreibung (Karma setzen auf) - 2 Buttons, nur einer kann aktiv sein
Abschicken Button

DNumSlider sollte automatisch die Minimal- und Maximalwerte setzen.

**Comment by doctorluk** [comment]
Sollte möglich sein, allerdings ist das bei mir recht niedrig auf der Prioritätsliste. Das Update hat noch einige anderen Sachen bei mir kaputt gemacht und darum werde ich mich erst mal kümmern. In Zukunft könnte man über eine GUI Implementation nachdenken. Mal sehen, wann ich Zeit dafür habe. Es ist allerdings nicht so schwer, wie es den Anschein macht.

**Comment by doctorluk** [comment]
Falls du mit 213b52bb91fb9db02511c121e56f5e678d8c6152 einverstanden bist oder du Feedback hast, lass es mich wissen.
Hier ein paar Screenshots:
![image](https://cloud.githubusercontent.com/assets/6282654/21581819/781c4fcc-d041-11e6-89b8-619e59d420e8.png)
![image](https://cloud.githubusercontent.com/assets/6282654/21581820/7cbe00ac-d041-11e6-8d16-232705147ae0.png)
![image](https://cloud.githubusercontent.com/assets/6282654/21581821/7f7eff62-d041-11e6-8132-6e98de9a1a99.png)
![image](https://cloud.githubusercontent.com/assets/6282654/21581823/8124b9ba-d041-11e6-8b59-ccbb2afaf1f4.png)

**Comment by MinIsMin** [comment]
Sieht gut aus, habe derzeit nichts daran auszusetzen.
